services:
  wildguide:
    # image: mywild/wildguide:latest
    build: .
    container_name: wildguide
    volumes:
      - ./data:/app/data
    stop_signal: SIGKILL
    tty: true
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - JWT_AUDIENCE=test
      - CORS=${CORS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
