spring:
    application:
        name: WildGuide
    main:
        lazy-initialization: true
    jmx:
        enabled: false
    lifecycle:
        timeout-per-shutdown-phase: 30s
    config:
        import: optional:file:./.env[.properties]
    sql:
        init:
            mode: always
            schema-locations: 
                - classpath:sql/schema-tables.sql
                - classpath:sql/schema-indexes.sql
                # - classpath:sql/schema-v1.sql
            # data-locations:
                # - classpath:sql/data-v1.sql
    datasource:
        # Some noteworthy settings: DB_CLOSE_DELAY=-1; DB_CLOSE_ON_EXIT=FALSE; CACHE_SIZE=131072; AUTO_SERVER=TRUE; AUTO_SERVER_PORT=9090;
        url: jdbc:h2:file:./data/wildguide;AUTO_SERVER=TRUE
        driverClassName: org.h2.Driver
        username: wildguide
        password: wildguide
    h2:
        console:
            enabled: false
            path: /h2-console

server:
    port: 8080
    compression:
        enabled: true
        min-response-size: 1KB
    error:
        whitelabel:
            enabled: false
        include-message: always
        include-binding-errors: always
        include-exception: true
        # include-stacktrace: always
    shutdown: graceful

springdoc:
    swagger-ui:
        persist-authorization: true
        filter: true
        tags-sorter: alpha

logging:
    include-application-name: false
    include-application-group: false
    level:
        # Spring default log level (affects the application - both console and file)
        root: INFO
        # Used in the logback-spring.xml to set a lower (than root) log level for the console
        console: ERROR
        # Overwrite log level for specific code packages
        mywild: INFO

mywild:
    app:
        name: @project.name@
        version: @project.version@
        devMode: false
    jwt:
        issuer: MyWild
        subject: WildGuide
        audience: ${JWT_AUDIENCE}
        access-token-duration: 60
        refresh-token-duration: 362
    key:
        private: ${PRIVATE_KEY}
        public: ${PUBLIC_KEY}
    cors: ${CORS}
    wildguide:
        concurrent-users-limit: 100
        user-rate-limit: 75
        global-rate-limit: 3000
        page-size: 50
        inat-results-per-page: 200
